name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build Debug APK
      run: ./gradlew assembleDebug
    
    - name: Build Release APK
      run: ./gradlew assembleRelease --stacktrace || true
    
    - name: Upload APK to Artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: APK
        path: |
          app/build/outputs/apk/debug/app-debug.apk
          app/build/outputs/apk/release/*.apk

    - name: Create Release
      if: success()
      uses: softprops/action-gh-release@v1
      with:
        files: |
          app/build/outputs/apk/debug/app-debug.apk
        tag_name: build-${{ github.run_number }}
        body: "Task Gamifier APK Build"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
